baseURL = "https://hamzadastagir.github.io/"
languageCode = "en-us"
title = "Hamza Dastagir's Portfolio"
theme = "console"

[params]
  # Basic Info
  author = "Hamza Dastagir"
  description = "Portfolio of Hamza Dastagir"
  # Disable footer
  hideFooter = true

  # Console Configuration
  enableAnimations = true
  enableCursorBlink = true
  enableShellPrompt = true
  enableAutocomplete = true
  enableNavbar = true

# Menu Configuration
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    name = "Papers"
    url = "/papers/"
    weight = 4

  [[menu.main]]
    name = "Trading"
    url = "/trading/"
    weight = 5
