name: github pages

on:
  push:
    branches:
      - main # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   submodules: true # Fetch Hugo themes (true OR recursive)
        #   fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      
      - name: Cache Hugo
        uses: actions/cache@main
        with:
          path: |
            resources/
            hugo_cache/
          key: ${{ runner.os }}-hugo

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'yarn'

      - name: Install Node packages
        run: yarn install --frozen-lockfile
        # run: yarn install --frozen-lockfile --production=true # this prevents install of devDependencies

      - name: Build
        run: hugo --environment production --gc --cacheDir "${GITHUB_WORKSPACE}/hugo_cache"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public