# name: Deploy React App to GitHub Pages

# on:
#   push:
#     branches:
#       - main  # Deploy on push to main
#   pull_request:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       # 1. Checkout the repository code
#       - uses: actions/checkout@v3

#       # 2. Setup Node.js environment (using Yarn caching)
#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#           cache: 'yarn'

#       # 3. Install dependencies
#       - name: Install Dependencies
#         run: |
#           if [ -f yarn.lock ]; then
#             yarn install --frozen-lockfile
#           else
#             yarn install
#           fi

#       # 4. Build the React app
#       - name: Build React App
#         run: yarn build

#       # 5. Deploy the build folder to GitHub Pages
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./build
